const mongoose=require("mongoose");
const userdata=require("./userschema.js")
const kittySchema=new mongoose.Schema({
    shippinginfo:{
        address:{
            type:String,
            required:true,
        },
        city:{
            type:String,
            require:true
        },
        state:{
            type:String,
            require:true,
        },
        country:{
            type:String,
            require:true
        },
        pincode:{
            type:Number,
            required:true
        },
        phone:{
            type:Number,
            // required:true
        }
    },
    orderitem:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                requied:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:"product",
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"user",
        required:true,
    },
    paymentinfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        },
    },
    paidat:{
        type:Date,
        required:true
    },
    itemprice:{
        type:Number,
        required:true,
        default:0,
    },
    taxprice:{
        type:Number,
        required:true,
        default:0
    },
    shippingprice:{
        type:Number,
        required:true
    },
    totalprice:{
        type:Number,
        required:true,
        default:0
    },
    orderstatus:{
        type:String,
        required:true,
        default:"processing"
    },
    deliveredat:Date,
    createtedat:{
        type:Date,
        default:Date.now,
    },



});
const orderdata=mongoose.model("order",kittySchema);
module.exports=orderdata;